name: CI Pipeline

on:
  push:
    branches:
      - main
      - release
  pull_request:
    branches:
      - master
      - release
      - develop

jobs:
  python-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Output personal information
        run: |
          echo "Full Name: Garifullin Vadim Salavatovich"
          echo "Group Number: 3117"
          echo "GitHub username: $GITHUB_ACTOR"

      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with pytest
        run: |
          export PYTHONPATH=$PYTHONPATH:.
          pytest --maxfail=1 --disable-warnings -q

      - name: Check code style with black
        run: black .

      - name: Format code with black (optional)
        run: |
          pip install black
          black .  # Автоматическое исправление стиля

